### ISSUE TITLE
Something wrong with `daemon_strategy`

### ISSUE THREAD

**Issue by aratak** [dmitriy-kiriyenko/soprano#5]
Just updated to lates verson, but got an error.

hotfixed by `set :daemon_strategy, ""`

```
aratak@masmodeus:~/projects/vecherka {master}$ cap deploy
    triggering load callbacks
/Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/variables.rb:82:in `fetch': `daemon_strategy' not found (IndexError)
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/variables.rb:110:in `protect'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/variables.rb:110:in `synchronize'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/variables.rb:110:in `protect'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/variables.rb:78:in `fetch'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/soprano-0.60/lib/../recipes/daemon_strategy.rb:2:in `load'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/callback.rb:25:in `call'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/callback.rb:25:in `call'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/callbacks.rb:123:in `trigger'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/callbacks.rb:123:in `each'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/configuration/callbacks.rb:123:in `trigger'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/cli/execute.rb:33:in `execute!'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/gems/capistrano-2.11.2/bin/cap:4
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/bin/cap:19:in `load'
    from /Users/aratak/.rvm/gems/ruby-1.8.7-p352@vecherka/bin/cap:19
```

**Comment by dmitriy-kiriyenko** [comment]
Resolved, sry.
